# version: '3.8'

# services:
#   backend:
#     image: diyanpratama/rent-api:latest
#     ports:
#       - "3000:3000"

#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - "80:80"
#     depends_on:
#       - backend

version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production

# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "5432:5432"
#     networks:
#       - app_network

#   app:
#     build: 
#         context: .
#         dockerfile: Dockerfile
#       platform: linux/amd64
#       ports:
#         - "8080:80"
#       environment:
#         - NODE_ENV=production
#         - DB_HOST=db
#         - DB_USER=${DB_USER}
#         - DB_PASSWORD=${DB_PASSWORD}
#         - DB_NAME=${DB_NAME}
#     networks:
#       - app_network

# networks:
#   app_network:
#     driver: bridge