name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/project/RentalCoreAPI
            docker-compose down # Shutdown the running containers
            docker-compose pull # Pull the latest updates
            docker-compose up -d # Restart the containers in detached mode
            # Check if Docker container is running on port 80
            sudo lsof -i :80 || echo "No service is using port 80"
